//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ProductoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoServiceReference.IExaCatalogoProducto")]
    public interface IExaCatalogoProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaCatalogoProducto/Add", ReplyAction="http://tempuri.org/IExaCatalogoProducto/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProyectoENT.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProyectoENT.ExaCatalogoProducto))]
        ProyectoENT.Result Add(ProyectoENT.ExaCatalogoProducto exaCatalogoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaCatalogoProducto/Add", ReplyAction="http://tempuri.org/IExaCatalogoProducto/AddResponse")]
        System.Threading.Tasks.Task<ProyectoENT.Result> AddAsync(ProyectoENT.ExaCatalogoProducto exaCatalogoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaCatalogoProducto/GetAll", ReplyAction="http://tempuri.org/IExaCatalogoProducto/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProyectoENT.ExaCatalogoProducto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        ProyectoENT.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaCatalogoProducto/GetAll", ReplyAction="http://tempuri.org/IExaCatalogoProducto/GetAllResponse")]
        System.Threading.Tasks.Task<ProyectoENT.Result> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExaCatalogoProductoChannel : PL.ProductoServiceReference.IExaCatalogoProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExaCatalogoProductoClient : System.ServiceModel.ClientBase<PL.ProductoServiceReference.IExaCatalogoProducto>, PL.ProductoServiceReference.IExaCatalogoProducto {
        
        public ExaCatalogoProductoClient() {
        }
        
        public ExaCatalogoProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExaCatalogoProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExaCatalogoProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExaCatalogoProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoENT.Result Add(ProyectoENT.ExaCatalogoProducto exaCatalogoProducto) {
            return base.Channel.Add(exaCatalogoProducto);
        }
        
        public System.Threading.Tasks.Task<ProyectoENT.Result> AddAsync(ProyectoENT.ExaCatalogoProducto exaCatalogoProducto) {
            return base.Channel.AddAsync(exaCatalogoProducto);
        }
        
        public ProyectoENT.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ProyectoENT.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
